### ISSUE TITLE
Support: 1.19.x

### ISSUE THREAD

**Issue by cerealconjugo** [Chikage0o0/EMICompat#1]
It is planned to get support for newer versions?

**Comment by Chikage0o0** [comment]
> It is planned to get support for newer versions?

I will allow 1.19 loading in the next release, you can try it, but I do not guarantee no problems.
Full support will have to wait until CreateOrigin version is updated to 1.19.

**Comment by Chikage0o0** [comment]
> It is planned to get support for newer versions?

Version 1.19 of EMICompat will not be available until CreateOrigin is upgraded to 1.19, unless someone else helps.

**Comment by cerealconjugo** [comment]
i will try the next release as you say for now. Thank u

**Comment by lxly9** [comment]
You can actually just update fabric.mod.json with minecraft: 1.19.x and emi: 1.19. and it works
