### ISSUE TITLE
AE2 search sync support?

### ISSUE THREAD

**Issue by leo60228** [Chikage0o0/EMICompat#12]
In addition to the recipe integration for JEI/REI, AE2 supports syncing the search bar in a terminal. As far as I can tell there isn't currently an API in AE2 for this, but it looks easy to implement with a mixin: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d6b1a2d365f47422866c7f1391445668624f9eae/src/main/java/appeng/util/ExternalSearch.java

**Comment by Chikage0o0** [comment]
There is already official intent to support emi, so I'm not going to provide that feature for now.
