### ISSUE TITLE
I created an updated version for Farmer's Delight on 1.19.2

### ISSUE THREAD

**Issue by nnmrts** [Chikage0o0/EMICompat#3]
I did a thing: https://github.com/nnmrts/emi_farmersdelight

Nothing special, but since it's a fork of this project I thought I'd let you know. I have absolutely no Java experience at all combined with absolutely no mod development experience, so please let me know if I did something wrong or didn't credit your work appropriately.

It's on Modrinth here: https://modrinth.com/mod/emi_farmersdelight (might take some time until it's reviewed)

Sorry for creating an issue for this but I didn't know any other appropriate way of telling you about this.

EDIT: Also let me know if you are interested in taking over the project, since I won't really be able to maintain it and I will probably only update it when it's necessary for me personally (aka my game crashes :D).

**Comment by Chikage0o0** [comment]
I will merge your commits and provide support for AE2 and release the 1.19.2 update in the near future.

**Comment by nnmrts** [comment]
@Chikage0o0 Awesome! Feel free to let me know when that has happened (either by @-ing me in here or closing the issue) so I can update the readmes of my repo on GitHub and Modrinth, adding a "deprecation message" and a link to your project.
