### ISSUE TITLE
CurseForge Release?

### ISSUE THREAD

**Issue by gamerpotion** [Chikage0o0/EMICompat#6]
Hi, just wondering if this is something you would officially release on CurseForge? 
so can include it on my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg

**Comment by Chikage0o0** [comment]
I'm very sorry, I don't intend to release a version in Curseforge.

**Comment by gamerpotion** [comment]
Ok No worries, 
thanks for the quick reply.
