### ISSUE TITLE
Tech Reborn Support

### ISSUE THREAD

**Issue by Kneelawk** [Chikage0o0/EMICompat#8]
# The Issue
Last I spoke to the TR devs, EMI support seemed out-of-scope for what they planned.

I am wondering if EMICompat is a good place for this compat or if it should instead be part of a different addon?

**Comment by Kneelawk** [comment]
I'm hoping to start work on this as a separate addon which I should easily be able to merge into EMICompat if deemed appropriate.

**Comment by Chikage0o0** [comment]
I am more than welcome and supportive of your code merging into EMICompat, but you will also need to provide maintenance  after the merge.
